src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java, src/test/java/BQJDBC/QueryResultTest/BQResultSetFunctionTest.java, src/test/java/BQJDBC/QueryResultTest/BQScrollableResultSetFunctionTest.java, src/test/java/BQJDBC/QueryResultTest/GrammarTest.java, src/test/java/BQJDBC/QueryResultTest/QueryResultTest.java, src/test/java/BQJDBC/QueryResultTest/Timeouttest.java
it appears as though the public shakespeare data got out of sync again. This appears to have happened before
The original authors wrote in the comments at one point " somehow the result changed with time" As this is supposed to
be a corpus of shakespeare's works, I don't see how the wordcount could have changed.
Original commit/change mentioned here: https://github.com/jonathanswenson/starschema-bigquery-jdbc/blob/cb0d718c95409316c4ee05c992b08d7135c52cd0/src/test/java/BQJDBC/QueryResultTest/BQResultSetFunctionTest.java#L329
Anyway, it appears to have reverted back to what it originally was, hopefally it doesn't change again...
There was also one test that seems to have started failing, stating that the dataset was not specified.
I added the dataset for the test to make sure it was passing …
=> Fix shakespeare dataset tests.

src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java
Made number very very very large. Turns out there is a way to scroll through the results from the API, but that would require rewriting a very significant chunk of the driver. I'm going to switch BigQuery's `information_schema` off JDBC soon enough, but this should tide us over until we get there. 
If this seems too objectionable, then I'll just block bigquery PDTs on rewriting the information schema. What do you think?
=> Removed limit on table listing completely

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/BQJDBC/QueryResultTest/CancelTest.java
Threw in the ability for a BQConnection to cancel all of its current queries. This shouldn't affect anything for anyone not using cancel().
=> Query cancel

pom.xml, src/main/java/net/starschema/clouddb/cmdlineverification/Oauth2Bigquery.java, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQDriver.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java
Slightly more reusable approach to parameter parsing. All parsed params
are now fully case insensitive (before it was only url parameters that were
fully case sensitive, while params passed in the Properties were only partially
case insensitive.
While it was implicitly done on a case by case basis before, now all jdbc url
parameters will override anything in the login properties. I don't believe that
this is standard in JDBC drivers (though I could be wrong here), this was the
original behavior and I would like to maintain it for backwards compatibility.
Additionally, this PR adds another JDBC property that can be read from the
JDBC url or the login properties to set the userAgent on all BigQuery Requests
from an authenticated BigQuery instance. If this parameter is not used, no
user …
=> Refactor connection param parsing + add userAgent param

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java
BigQuery Standard SQL adds a date type. We should probably bring some of the other ResultSets
up to speed on timestamps/dates.
@stalbot Any thoughts about this one?
=> Add date type to ForwardOnlyResult Set.

pom.xml, src/main/java/net/starschema/clouddb/cmdlineverification/Oauth2Bigquery.java, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java
The default value is still the same for both (20s), but can now be configured by specifying the readTimeout/connectTimeout parameters in the JDBC url / connection properties.
=> Add the ability to set the read/connect timeout 

pom.xml
Need a newer version of the google-api-client which includes clustering and location support.
=> bump dependencies support location and cluster by

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java
1. Bump default timeout to 240s, which according to Google is the timeout on their backend.
1. Make sure the job id shows up the error message we throw when the result fetch fails.
1. Add some retries into our result fetch.
=> Add some resiliency to the API interactions

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java
~Obviously the format here could be better. This is taking the underlying data from what I assume is the d-jsonified BigQuery API response and re-JSONifying it. Going to at least glance at how hard it would be try to pull metadata out of the response and give things the right structure, rather than this naive JSONification. But if that looks like it will take a bit, it's still much much better to not explode.~
Fixed the format to return basically what you'd expect
=> Don't explode when you get an array or hash

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java, src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java
Match the known JDBC connection string for better parsing of the projectId in order to allow for colons in the projectId. If the expected connection string format is not matched then fallback to the old way of simply using the last occurence of a colon as the start index of the projectId/dataset path params.
While we're in here, fixup a test which expected HashMap serialization ordering to always be consistent.
=> Colons in dataset name

.gitignore, pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQDriver.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java, src/test/java/BQJDBC/QueryResultTest/CancelTest.java, src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java
See https://looker.atlassian.net/browse/MOD-90 for context. 
Add an `unlimitedBillingBytes` flag to `execute()` and `executeQuery()` so that we can specify in Helltool that BigQuery PDTs should bypass the Max Billing Gigabytes setting. Also includes tests. 
Also... fixes https://github.com/jonathanswenson/starschema-bigquery-jdbc/issues/22
=> Fix MaxBillingBytes Behavior for BigQuery PDTs

pom.xml
BQ revision 431 (https://developers.google.com/resources/api-libraries/documentation/bigquery/v2/java/latest/com/google/api/services/bigquery/Bigquery.Models.html) includes a new Model API.
=> Bump BQ revision

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQPreparedStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java, src/test/java/BQJDBC/QueryResultTest/PreparedStatementTests.java
As title suggests: add support for getting info about `DATE` and `RECORD`/`STRUCT`-type columns. 
Before this: `ResultSet.getMetaData().getcolumnType([index of a DATE-type column])` -> `Unsupported Type: DATE`
=> Add metadata support for dates and records

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java, src/test/java/BQJDBC/QueryResultTest/PreparedStatementTests.java
Note that `DATETIME` is not a native `java.sql.Types` type, so just categorize it as a `TIMESTAMP` when retrieving column types for `DATETIME`s.
=> Add metadata support for DATETIME data type

pom.xml, src/main/java/net/starschema/clouddb/cmdlineverification/Oauth2Bigquery.java, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java
This adds the ability to pass in an OAuth 2.0 access token in with the jdbc url to authenticate with a url param `oAuthAccessToken=`.
In order to test this, I also added a method to get an access token from Bigquery's API using service account credentials. So the test first gets the access token, and then runs a query using that token.
=> OAuth 2.0 Access Token Authentication

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java
Also moved language compatibility to Java 8 and so bumped to 2.0...
maybe bump to 2.0 is too aggressive? But I was _not_ going to use the Java legacy Date API to do this. And it's time for this project to be on 8.
As to the bug, prior to this change, since TIMESTAMPs come back in JSON over the wire as stringified BigInts, and getString was doing nothing special to handle that, the result for `SELECT CURRENT_TIMESTAMP` was something like `"1.234932532E9"`
=> Fix getString for TIMESTAMP types

pom.xml, src/main/java/net/starschema/clouddb/cmdlineverification/Oauth2Bigquery.java
in order to tell if a connection is using oauth, so we can check for oauth-specific 401 errors
this is similar to the user agent accessor that's on the same class.
=> Add oauth token accessor to bigquery request initializer

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java
`getObject` was relying on `getString` not doing anything special to these. Of course it turned out that we already had logic to deal with this elsewhere. (which I should have realized since this already worked in `getObject`). Sigh, oh well.
=> Um, fix datetime again?

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java, src/test/java/BQJDBC/QueryResultTest/PreparedStatementTests.java
Add `TIME` and `BYTES` as supported types. Also add full list of BQ types for reference.
=> Type parity between BQ and Starschema

dependency-reduced-pom.xml, pom.xml, src/main/java/net/starschema/clouddb/cmdlineverification/Oauth2Bigquery.java, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java, src/main/java/net/starschema/clouddb/jdbc/BQScrollableResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java, src/test/java/BQJDBC/QueryResultTest/CancelTest.java, src/test/java/BQJDBC/QueryResultTest/QueryResultTest.java
Had to do a bit of refactoring because parts of the code assume they have a BigQuery API `GetQueryResultsResponse` object. Instead, we need to have those parts of the code take a list of rows and a schema, so that when we get all the rows we need back from the synchronous API, which will be very frequently true since the limit there is 10MB, we don't want to have to go fetch more rows from BQ.
=> Switch driver to run with synchronous jobs.query endpoint

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java
Now, with the synchronous route, this is the place where users see issues with their SQL in the form of exceptions, so we should not muddy it up with the whole querySql the way the previous version of the code did.
=> Don't include querySql in query execution error message

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/test/java/BQJDBC/QueryResultTest/CancelTest.java
Essentially, once a connection is closed, `getBigQuery` returns null, so we have to check here in case some other thread closed our connection as a way to cancel the running statements.
Then there's some finessing of the test code to get a test for this to work.
=> Fix issue with the sync bq api and connection close

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java, src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java
Introduce new `getColumnMode(int index)` accessor on `BQResultSetMetadata` to allow consumers to determine whether results are arrays or not. 
Also change behavior to return raw string values for "REPEATED"-mode values (arrays) so that consumers can interpret/convert types as needed. 
Note that `getObject()` and `getString()` will behave identically for arrays: both will return the raw string value of the result.
=> Implement basic driver support for ARRAY types

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/test/java/BQJDBC/QueryResultTest/QueryResultTest.java
This path was broken for any query that did not fetch all the rows in the initial load in non-US/EU locations, because it did not call `setLocation` when getting the job.
=> Fix sync query api path for non-US/Eu locations

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/BQJDBC/QueryResultTest/CancelTest.java
Cancel code relied on existence of a `job` on `BQStatement`, but that was only set (only could be set) by the async code. We need to wait for the sync code to time out, then cancel the query. 
Without further change here, this means that the absolute fastest a query can be cancelled is ten seconds. We can reduce the ten seconds (it's just a constant we control) but that means more queries would miss on the sync endpoint and have to poll, so it's a bit of a trade-off. For now, will reduce the sync time to five seconds in this PR. We could also enable that to be controlled by a connection parameter in the future for folks who really want to tune, but don't bother for right now because it's not clear at five seconds plus how much benefit the sync endpoint gives you anyway.
=> Fixup the way the sync query code handles cancelling a job by reference

src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/test/java/BQJDBC/QueryResultTest/CancelTest.java
There is some undesirable behavior where in the sync query mode, we will cancel the job on `Statement#close` even though the job is already done. BigQuery happily tells us "this job is already done" and moves on, but no point initiating an API request to BQ in the general `stmt.close` case (surely slows down queries), so let's make sure to clean up after ourselves by nulling out `syncResponseFromCurrentQuery` (and change its name so that it's more obviously something that only stays around for the current query's lifecycle).
This is ultimately a bug, in that if you don't have permission to execute a cancel, this means that the normal flow where you make a Statement, execute a query, and then close the statement throws an exception, so add a test hat we are not calling cancel at the end of …
=> Make the sync response null when the query completes

src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/test/java/BQJDBC/QueryResultTest/QueryResultTest.java
Some `dbcp2` expects `(get|set)Scehma` to work if a schema is set on the connection, here we implement.
From `dbcp2`:
=> Implement Schema Methods

src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQDatabaseMetadata.java, src/main/java/net/starschema/clouddb/jdbc/BQPreparedStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/main/java/net/starschema/clouddb/jdbc/CatalogName.java, src/test/java/BQJDBC/QueryResultTest/CancelTest.java, src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java
A prior version of this driver supported translating between SQL-92 and
BigQuery Legacy dialects.  As part of this support, it would mangle
BigQuery Project Ids like `looker.com:sample-project` to
`looker_com__sample-project`.  We found that there were some bugs in
this translation leading to the mangled name being sent to BigQuery when
the real ProjectId should have been sent.
We recently removed support for this translation between dialects.
Since we no longer require that, we can now remove most of the code
which did the name mangling.
In this PR, we fix on using the Project Id internally as much as
possible.  Only in public methods of the JDBC API do we accept a Catalog
name.  All internal methods translate this to a Project Id before doing
any further processing of them.
We do retain …
=> Remove support for Catalog -> ProjectId name mangling

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java
Previously, the unnecessary parsing to BigDecimal would explode on NaN (and Inf, etc). Double.parseDouble has no problem with this.
=> Fixup NaN values in double types

src/main/java/com/google/api/services/bigquery/MinifiedBigquery.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java, src/test/java/BQJDBC/QueryResultTest/QueryResultTest.java
According to feedback from the BigQuery team there is significant overhead in the whitespace processing for BigQuery pretty printed JSON.
They recommend disabling it and they call out bigquery.jobs.getQueryResults and bigquery.tabledata.list as the big winners.
It was kind of tedious to turn it off for every API call, so I introduce a new proxy _Bigquery_ class that sets it for every request type.
=> Disable pretty printing by default

README.md, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java, src/test/resources/vpcaccount.properties
Enable using e.g. `rootUrl=https%3A%2F%2Fcustom.bq.com%2F` (URL-decoded: `https://custom.bq.com/`) to hit alternative endpoints to `https://bigquery.googleapis.com/`.
I've added a new properties file for the test and just checked it in since it does not contains any secrets per se (though it references `bigquery_credentials.p12` even though it doesn't make any real requests). I can also just add it to the zip archive that I uploaded to Secret Manager for easier distribution of the files. I also included instructions in the README for accessing those secrets, which are accessible to everyone in the `cloud-looker-model-dev@google.com` group and could potentially be made available to others if we want to.
=> Add support for custom root URL via JDBC parameter

src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
The driver will now accept per-statement labels in addition to the per-connection labels. It checks to make sure it doesn't send more than the [max of 64 labels per query](https://cloud.google.com/bigquery/docs/labels-intro#requirements), but doesn't check anything else about label validity. I have an accompanying PR for Looker to make use of this. This introduces an auxiliary API that is not typical of JDBC drivers and would not normally be used by "typical" users of this driver. As such, it is end-to-end tested in helltool, but not here.
=> Add support for sending per-statement labels

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQScrollableResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java, src/test/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSetFunctionTest.java, src/test/java/net/starschema/clouddb/jdbc/BQScrollableResultSetFunctionTest.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java, src/test/java/net/starschema/clouddb/jdbc/QueryResultTest.java
I'm unsure exactly how to assert in the test since these values may or may not be subject to change. Documentation is underspecified. This seems to work.
=> Record total_bytes_processed and cache_hit on results sets

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/test/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSetFunctionTest.java
Super similar to https://github.com/jonathanswenson/bqjdbc/pull/92. 
Found that async queries suffer from the same poor primitive unboxing as sync queries, resulting in NPE.
=> Fix result set NPE for procedure creation during async query

src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
This adds a new query parameter `queryCache` that can be used to disable BigQuery's cache. By default, the cache is enabled, but if the user sets this param to anything other than `true` (case-insensitive), it will be disabled.
Also does a bit of refactoring for the labels logic so that per-statement labels are no longer ignored when the query execution logic goes through `BQStatementRoot` rather than `BQStatement`. I'm not sure this would ever be an issue for Looker, but figured it's worth patching and adding a unit test.
=> Add support for 'queryCache' parameter

src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
Addresses FR raised [here](https://yaqs.corp.google.com/eng/q/4918674062948958208?team_name=2398870489016565760) by adding support for a `timeoutMs` param which overrides the default query timeout of `Integer.MAX_VALUE / 1000 - 1` 
The FR mentions the [`jobTimeoutMs` param](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfiguration) but the driver only creates a `JobConfiguration` for prepared statements which (from my understanding) aren't used in Looker. So, I figured `timeoutMs` would get close enough.
Happy to change anything or drop it altogether -- seemed like an easy add 👍 
Clone of closed PR: https://github.com/jonathanswenson/bqjdbc/pull/107
=> Add `timeoutMs` URL param

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQScrollableResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java, src/test/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSetFunctionTest.java, src/test/java/net/starschema/clouddb/jdbc/BQScrollableResultSetFunctionTest.java
Being null can be significant, especially in light of row-level ACLs, for which `totalBytesProcessed` is set to null to prevent users from inferring things they shouldn't know about the table. Let's just let the total bytes processed and cache hit metrics be null. We'll just neglect to emit the Pinger metrics in Looker if they're null.
Also add some more tests. Testing null-readiness is really annoying since so many things can be null. Open to suggestions on how I might test this better.
=> Allow totalBytesProcessed and cacheHit to be null

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java
Switches from the authentication in
com.google.api.client.googleapis.auth.oauth2.GoogleCredential to
com.google.auth.oauth2.GoogleCredentials.  The former is deprecated and
does not support the newer authentication mechanisms that the latter
does.  This switch should let us use the latest authentication
mechanisms specified in the google credentials json file, such as
external authentication.
=> Upgrade google clients

pom.xml, src/main/java/net/starschema/clouddb/jdbc/DMDResultSet.java
I added spotless to maven previously, but forgot to include it in the `verify` step.  This ensures that it will cause CI to fail if bad changes are checked in.
=> Enforce spotless check during validate

src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
Updating the google auth library changed the behavior of handling an
invalid oauth token.  Previously, it would return a failure response as
Unauthorized.  With the change, an interaction in the google libraries
would cause it to throw an IllegalStateException.
This change smooths over that interaction so that we can return an
Unauthorized response as we did before.
=> Return Unauthorized when using invalid OAuth token

.github/workflows/build.yml, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
Adds support for `withApplicationDefaultCredentials` param that will use the [application default credential](https://cloud.google.com/docs/authentication/production#automatically) to authenticate a BQ connection. This param takes the lowest precedence over other auth methods if multiple are provided for some reason:
1) `withServiceAccount` - use service account file.
2) `oAuthAccessToken` - use the provided OAuth token.
3) `withApplicationDefaultCredentials` - use application default.
This is part 1 of 2 to assist in adding service account impersonation to Looker.
**NOTE**: Tests will almost certainly fail due the public `shakespeare` dataset being out of commission as of earlier today Most of our tests use this dataset to here's hoping that gets resolved soon.
=> [b/198504533] Adds support for Application Default Credentials flag as URL param

.github/workflows/build.yml, pom.xml, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
Sets the `GOOGLE_APPLICATION_CREDENTIALS` environment variable for the `JdbcUrlTest` class so tests that need it are guaranteed to have it set.
=> Set default application credentials path for test runs

.github/workflows/build.yml, src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
Adds a new URL param `targetServiceAccount=<String>` to allow for [service account "impersonation"](https://cloud.google.com/iam/docs/impersonating-service-accounts) e.g. `targetServiceAccount=<service-account>@<project>.iam.gserviceaccount.com` 
Choosing an auth method is still required so, for example, `withApplicationDefaultCredentials=true&targetServiceAccount=<service-account-email>` would use the application default as source and attempt to impersonate the target account.
This should work fine for `withServiceAccount` and `withApplicationDefaultCredentials`. I _think_ this should be fine for `oAuthAccessToken` also but I have yet to verify (should probably do that). 
One thing to note, the [docs](https://cloud.google.com/iam/docs/impersonating-service-accounts#allow-impersonation) …
=> Adds support for service account impersonation 

src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java
I missed this when refactoring here: https://github.com/jonathanswenson/bqjdbc/pull/115 
Needed to set the OAuth token for `BigQueryRequestUserAgentInitializer` even if the `userAgent` wasn't explicitly provided. Tests elsewhere caught this but happy to put a test in here as well.
=> Ensure OAuth connections have a token set for their `BigQueryRequestUserAgentInitializer`

src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java, src/test/java/net/starschema/clouddb/jdbc/QueryResultTest.java, src/test/java/net/starschema/clouddb/jdbc/TimeoutTest.java
Adds support for [Service Account delegation](https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#sa-credentials-delegated) for impersonation. 
The `targetServiceAccount` param now accepts a comma separated list of SA emails (in order) to use as a delegation chain to access the "target" account.  The last SA will be used as the "target" account for impersonation.
For example `targetServiceAccount=<delegate-sa-1>,<delegate-sa-2>,<target-ccount>`
If a single SA is provided then it will simply be used as the impersonated account.
=> Adds support for SA delegates with impersonation.

pom.xml
This was added as a standard dependency rather than test dependency, correcting that here.
=> Mark assertj as a test dependency

src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java
Looks like we were setting the `projectId` param to be the `querySql` and then overwriting it by calling `setProjectId`. We set the `querySql` while building the `QueryRequest` so we were just doing this incorrectly. Wasn't causing any problems but probably good to correct it.
=> Prevent setting projectId for sync queries twice

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/test/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSetFunctionTest.java
Edge case was causing a NPE to be thrown when initializing `BQForwardOnlyResultSet`. The underlying issue seems to be a race condition where a connection is closed after the job has been completed but _before_ the driver has an opportunity to get the query results. Specifically, calling `close()` on a `BQConnection` sets its `bigquery` attribute to `null` so efforts to `getQueryResultsDivided` would fail. 
This just adds an additional check to see if `bigquery` is null and throws a more informative exception.
=> Prevent NPE if connection is closed before result set is initialized 

src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/test/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSetFunctionTest.java, src/test/java/net/starschema/clouddb/jdbc/CancelTest.java
A NPE could be thrown within `BQStatement.runSync` for long running queries. Doesn't happen often but if the BQ project has a reservation quota that's reached while polling for a query job to finish then check for its current state might return an incomplete `Job`. 
We now throw an `IOException` in that case which will at least retry the polling query rather than bubbling up a NPE.
=> Check for empty jobs response when polling for query completion

src/main/java/net/starschema/clouddb/jdbc/BQConnection.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java, src/test/resources/sampleaccount.properties, src/test/resources/vpcaccount.properties
When using SA impersonation we need to explicitly set a quota project that will be used for billing services. Here we add the `projectId` specified in the JDBC URL as the quota project when constructing the `ImpersonatedCredentials` to use. This effectively makes the `projectId` declared in the URL the billing project that will be used for all BQ jobs.
=> feat: set quota project when using impersonation

README.md
Badges referenced com.looker but it's com.google
=> Fixed javadoc and img.shield badge

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQStatement.java, src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java
Uses [Optional](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) to make fetching BI Engine statistics null-safe.
=> fix: NullPointException when statistics query is null

pom.xml, src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java
bqjdbc uses com.google.guava:guava as a transitive dependency. It needs to be bumped from 31.1-jre to 32.0.1-jre per
https://osv.dev/vulnerability/GHSA-7g45-4rm6-3mm3.
Also added the google-cloud-bigquery dependency, so that we don't have to pick out specific libraries from the Google Java client.
Since JacksonFactory is deprecated
https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.json.jackson2,
now using com.google.api.client.json.gson.GsonFactory instead.
Remove com.google.api.services.iamcredentials.v1 and now use Explicit
Credential Loading
https://github.com/googleapis/google-auth-library-java/blob/main/README.md#explicit-credential-loading
to generate an access token.
=> Update com.google.guava:guava dependency to v32.0.1-jre

src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java, src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java, src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java, src/test/java/net/starschema/clouddb/jdbc/PreparedStatementTests.java
* we were redundantly setting the OAuth Token in query parameter via `BigQueryRequestUserAgentInitializer#initializeBigqueryRequest`.
* The `HttpRequestTimeoutInitializer` which builds the `HttpRequest` was already setting it in the header of the request, which is the accepted method.
* remove the call to `setOauthToken` and associated code which is no longer required.
* in service of http://b/294919784
=> Remove OAuth Token From Query Params

pom.xml
Update com.google.cloud:google-cloud-bigquery to 2.34.0. The 2.29.0 version of com.google.cloud:google-cloud-bigquery uses org.json:json version 20230618 as a transitive dependency, which has a vulnerability listed here: https://osv.dev/vulnerability/GHSA-rm7j-f5g5-27vv. 2.34.0 uses a newer version of org.json:json, 20231013.
=> Update google-cloud-bigquery to 2.34.0

src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java, src/main/java/net/starschema/clouddb/jdbc/BQScrollableResultSet.java, src/main/java/net/starschema/clouddb/jdbc/DateTimeUtils.java, src/test/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSetFunctionTest.java
This change affects the way BigQuery's `TIME`, `TIMESTAMP`, and `DATETIME` types are handled in result sets.
- Adds support for microsecond precision in `getObject()`, `getString()`, and `getTimestamp()` for all types.
- `getObject()` will return a `java.sql.Timestamp` object for `TIMESTAMP` and `DATETIME`. Previously, it returned `String` for `DATETIME`.
- `getObject()` will return a `java.sql.Time` object for `TIME`. Previously, it threw an error.
=> Use recommended semantics for getObject of date/time types

pom.xml, src/main/java/net/starschema/clouddb/jdbc/DateTimeUtils.java, src/test/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSetFunctionTest.java
Addressing http://b/317390864.
=> Add fix for null-valued TIMESTAMP

pom.xml
This CL bumps the minor version of the BQJDBC driver. In a recently merged PR[0], we added the ability to configure a default dataset project id, which is used in conjunction with the dataset id to locate unqualified table references. We added this new capability in a backwards compatible manner.
[0] https://github.com/looker-open-source/bqjdbc/pull/201
=> Prepare for v3.2.0 release
