src/main/java/net/starschema/clouddb/jdbc/BQConnection.java
src/main/java/net/starschema/clouddb/jdbc/BQStatement.java
src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java
src/main/java/net/starschema/clouddb/jdbc/list/SourceTable.java

I didn't add tests here because it will be tested elsewhere upstream and the test files here kind of scare me, but I can if you think it would be worth it.

Added datasets to the jdbc url

---

src/main/java/net/starschema/clouddb/jdbc/BQPreparedStatement.java
src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java
src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java

Here are some tests and a few fixes for... compilations errors? Somehow Maven package was perfectly happen to compile the code and pass the tests with the existing code, but then intellij noticed the below. (Maybe has to do with not doing `mvn clean`?) So, looks like we should get this one in quickly. Always good for one's code to compile!

Tests and fixes for new url functionality

---

src/main/java/net/starschema/clouddb/cmdlineverification/Oauth2Bigquery.java
src/main/java/net/starschema/clouddb/jdbc/BQConnection.java
src/main/java/net/starschema/clouddb/jdbc/BQDriver.java
src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java
src/test/java/BQJDBC/QueryResultTest/CancelTest.java
src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java

Changes so the the user can pass in a password via the JDBC url by passing in a path. Old functionality still works (no path, password is assumed to be a path to a p12 file with password 'notasecret'.).

Auth enhance

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java

Pretty self explanatory. 100 is way too low!

Bump fetch size for BigQuery to much higher number

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java
src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java

In forward only result set, support DATETIME and NUMERIC types, and better fallback for when we don't know a type

Better type support

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java
src/test/java/BQJDBC/QueryResultTest/QueryResultTest.java

extract the location from the jobReference and set it on calls to
jobs().get(), jobs().getQueryResults(), and jobs().cancel()

support location detection / specification

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java
src/test/java/BQJDBC/QueryResultTest/PreparedStatementTests.java

Also add test to confirm that the type checking works.

Add metadata support for NUMERIC data type

---

pom.xml
src/main/java/net/starschema/clouddb/cmdlineverification/Oauth2Bigquery.java
src/main/java/net/starschema/clouddb/jdbc/BQConnection.java
src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java

To get this new test to work, you will need a JSON auth file and a protectedaccount-json.properties file locally.

Json auth in props support

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java

...and they have the expected string formatting
Also known as I forgot that CI doesn't run on PRs here.

So DATETIME types are also type code timestamp

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQForwardOnlyResultSet.java
src/test/java/BQJDBC/QueryResultTest/BQForwardOnlyResultSetFunctionTest.java

Add support for BigQuery's TIME type, which is essentially a TIMESTAMP without the DATE portion.

Add TIME support

---

src/main/java/net/starschema/clouddb/jdbc/BQStatement.java
src/test/java/BQJDBC/QueryResultTest/CancelTest.java

The old code was using the existence of the `currentlyRunningSyncThread` to check if we were in the sync case, but that thread was nulled out after the sync path completed! So make sure we also check for a `lastSyncResponse`.

Fix cancellation when the cancel comes after the sync part of the query has completed

---

.github/workflows/build.yml
src/test/java/BQJDBC/QueryResultTest/JdbcUrlTest.java
src/test/java/BQJDBC/QueryResultTest/QueryResultTest.java

:+1: Big thanks to @jonathanswenson for adding the secrets necessary to run this.
Testing, testing, testing
We now have testing for our jdbc driver; this repository is a bit **less** humiliating.
Turns out some of the tests are in fact broken because they rely on a certain ordering :+1: 
At least now we can run the tests more often and discover these broken ones.

Added github action

---

README.md

Also add 'History' section, reduce line length in the Java sample, and link to Maven Central.

In README, describe how to download and build

---

pom.xml

This is all we need to do, right?

Remove SNAPSHOT to start release

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java
src/test/java/net/starschema/clouddb/jdbc/PreparedStatementTests.java

Add BIGNUMERIC

---

pom.xml
src/main/java/net/starschema/clouddb/jdbc/BQResultSetMetadata.java
src/test/java/net/starschema/clouddb/jdbc/PreparedStatementTests.java

Add BIGNUMERIC support

---

src/main/java/net/starschema/clouddb/jdbc/BQStatementRoot.java

This is a followup to https://github.com/jonathanswenson/bqjdbc/pull/92.

Might as well check all the getters

---

pom.xml

Remove snapshot preemptive of new release.

Bump version to 2.3.8

---

src/main/java/net/starschema/clouddb/jdbc/BQSQLException.java
src/test/java/net/starschema/clouddb/jdbc/BQSQLExceptionTest.java
src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java

Should give more information related to #100

Enrich BQSQLExceptions with a little more information for ALL exceptions

---

pom.xml

Adds information about the "cause" of BQSQLExceptions to the message
for debugging purposes

Prepare version for new release for 2.3.10

---

pom.xml

Release for 2.3.18: https://github.com/looker-open-source/bqjdbc/releases/tag/v2.3.18

Set pom version to 2.3.19-SNAPSHOT

---

pom.xml

Prepare pom.xml for release v2.3.22

---

pom.xml

To incorporate https://github.com/looker-open-source/bqjdbc/pull/159

Prepare for 2.3.24 release

---

pom.xml

Prepare pom.xml for release v2.3.25

---

pom.xml

Prepare pom.xml for release v2.3.26

---

pom.xml

Fix BQJDBC use of OAuth Token to NOT send the token redundantly in API query parameters.

Update pom.xml for new release

---

pom.xml

Prepare pom.xml for release v2.3.28

---

src/main/java/net/starschema/clouddb/jdbc/BQSupportFuncts.java
src/main/java/net/starschema/clouddb/jdbc/Oauth2Bigquery.java
src/test/java/net/starschema/clouddb/jdbc/JdbcUrlTest.java
src/test/java/net/starschema/clouddb/jdbc/PreparedStatementTests.java

Reverts looker-open-source/bqjdbc#171
-- haven't had a chance to do a full integration test with Helltool, so reverting so other folks can cut new releases in the meantime.

Revert "Remove OAuth Token From Query Params"

---

pom.xml

Prepare pom.xml for release v2.3.29
